# Google Cloud Build configuration for ICT Eerbeek
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ict-eerbeek:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ict-eerbeek:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: 1800s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ict-eerbeek:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ict-eerbeek:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ict-eerbeek'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ict-eerbeek:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ict-eerbeek:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ict-eerbeek:latest'

# Build timeout
timeout: 2400s

# Machine type for build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
