version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: ict-eerbeek-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-ict_eerbeek}
      MYSQL_USER: ${DB_USER:-ict_eerbeek_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - ict-eerbeek-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ict-eerbeek-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: mysql://${DB_USER:-ict_eerbeek_user}:${DB_PASSWORD}@db:3306/${DB_NAME:-ict_eerbeek}
      JWT_SECRET: ${JWT_SECRET}
      VITE_APP_ID: ${VITE_APP_ID}
      OAUTH_SERVER_URL: ${OAUTH_SERVER_URL:-https://api.manus.im}
      VITE_OAUTH_PORTAL_URL: ${VITE_OAUTH_PORTAL_URL:-https://portal.manus.im}
      OWNER_OPEN_ID: ${OWNER_OPEN_ID}
      OWNER_NAME: ${OWNER_NAME:-ICT Eerbeek}
      VITE_APP_TITLE: ${VITE_APP_TITLE:-ICT Eerbeek}
      VITE_APP_LOGO: ${VITE_APP_LOGO:-/logo.png}
      BUILT_IN_FORGE_API_URL: ${BUILT_IN_FORGE_API_URL:-https://forge.manus.im}
      BUILT_IN_FORGE_API_KEY: ${BUILT_IN_FORGE_API_KEY}
      VITE_ANALYTICS_ENDPOINT: ${VITE_ANALYTICS_ENDPOINT:-}
      VITE_ANALYTICS_WEBSITE_ID: ${VITE_ANALYTICS_WEBSITE_ID:-}
    ports:
      - "3000:3000"
    networks:
      - ict-eerbeek-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ict-eerbeek-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - ict-eerbeek-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ict-eerbeek-network:
    driver: bridge

volumes:
  db_data:
    driver: local
